---
- apt: update_cache=yes

- name: Install postgresql
  apt: name=postgresql-{{postgresql.version.major}}.{{postgresql.version.minor}}-postgis-{{postgis.version.major}}.{{postgis.version.minor}} state=present